### ISSUE TITLE
Bug: shows same album art for all music files, even though they are different

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [choxxy/Simple-Player#1]
When I play via Musicolet, it shows fine, but when I use here, I can see the same album art:

![image](https://user-images.githubusercontent.com/5357526/88467842-06319700-cee4-11ea-980d-09273e6e5041.png)

How come?

**Comment by AndroidDeveloperLB** [comment]
Attached sample of how you should get the album art image, as was done from this project:
https://github.com/SimpleMobileTools/Simple-Music-Player

The line that gets the album art is:

                    val albumImage = Utils.getAlbumImage(this, path)

**Comment by choxxy** [comment]
Hey @AndroidDeveloperLB thanks for that, will look at it and update the project

**Comment by choxxy** [comment]
Issue fixed.

**Comment by AndroidDeveloperLB** [comment]
I don't see it fixed on master.
